# 엔티티별 개별 추출 프롬프트 정의

customer_name:
  prompt: |
    사용자의 발화에서 고객 이름을 추출하세요.
    
    추출 규칙:
    - 한글 이름만 추출 (2-4자)
    - "~입니다", "~이에요", "~예요" 등의 표현에서 추출
    - 성과 이름이 함께 있어야 함
    
    사용자 발화: "{user_input}"
    
    추출된 이름 (없으면 null):
  examples:
    - input: "저는 김철수입니다"
      output: "김철수"
    - input: "이름은 박영희예요"
      output: "박영희"
    - input: "최민수라고 합니다"
      output: "최민수"

# phone_number는 이제 사용하지 않음 (customer_phone으로 통합)

confirm_personal_info:
  prompt: |
    사용자가 개인정보 확인에 동의했는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 예, 맞아요, 맞습니다, 확인했어요, 동의합니다
    - 부정: 아니요, 아니에요, 틀려요, 수정할게요, 안 맞아요
    
    사용자 발화: "{user_input}"
    
    동의 여부 (true/false):
  examples:
    - input: "네, 맞습니다"
      output: true
    - input: "아니요, 틀려요"
      output: false
    - input: "네"
      output: true

use_lifelong_account:
  prompt: |
    사용자가 평생계좌 서비스 사용 의사를 표현했는지 판단하세요.
    
    판단 기준:
    - 평생계좌, 평생계좌번호 언급 시 의사 확인
    - 긍정: 사용, 할게요, 네, 좋아요
    - 부정: 안 써요, 필요없어요, 아니요
    
    사용자 발화: "{user_input}"
    
    사용 의사 (true/false/null):
  examples:
    - input: "평생계좌 사용하겠습니다"
      output: true
    - input: "평생계좌는 필요없어요"
      output: false
    - input: "평생계좌도 만들어주세요"
      output: true

ib_service_type:
  prompt: |
    사용자가 원하는 인터넷뱅킹 서비스 유형을 추출하세요.
    
    선택지:
    - "조회만": 잔액조회, 거래내역 조회만 가능
    - "조회+이체": 조회와 이체 모두 가능
    
    사용자 발화: "{user_input}"
    
    서비스 유형 (위 선택지 중 하나 또는 null):
  examples:
    - input: "조회만 되면 돼요"
      output: "조회만"
    - input: "이체도 할 수 있게 해주세요"
      output: "조회+이체"
    - input: "둘 다 가능하게 해주세요"
      output: "조회+이체"

ib_daily_limit:
  prompt: |
    사용자가 원하는 일일 이체 한도를 추출하세요.
    
    추출 규칙:
    - 숫자만 추출 (단위: 만원)
    - "백만원" → 100, "천만원" → 1000, "일억원" → 10000
    - 기본값은 제시하지 않음
    
    사용자 발화: "{user_input}"
    
    한도 금액 (숫자만, 없으면 null):
  examples:
    - input: "100만원으로 해주세요"
      output: 100
    - input: "한도는 500만원이요"
      output: 500
    - input: "천만원 한도로 설정해주세요"
      output: 1000

ib_security_method:
  prompt: |
    사용자가 원하는 보안 인증 방법을 추출하세요.
    
    선택지:
    - "SMS 인증": 문자 인증
    - "앱 인증": 모바일 앱 인증
    - "보안카드": 실물 보안카드
    
    사용자 발화: "{user_input}"
    
    인증 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "문자로 인증할게요"
      output: "SMS 인증"
    - input: "앱으로 하겠습니다"
      output: "앱 인증"
    - input: "보안카드 쓸게요"
      output: "보안카드"

cc_type:
  prompt: |
    사용자가 원하는 체크카드 종류를 추출하세요.
    
    선택지:
    - "일반형": 기본 체크카드
    - "교통카드형": 교통카드 기능 포함
    - "포인트적립형": 포인트 적립 기능
    
    사용자 발화: "{user_input}"
    
    카드 종류 (위 선택지 중 하나 또는 null):
  examples:
    - input: "그냥 일반 카드로 주세요"
      output: "일반형"
    - input: "교통카드 되는 걸로요"
      output: "교통카드형"
    - input: "포인트 쌓이는 걸로 할게요"
      output: "포인트적립형"

cc_delivery_method:
  prompt: |
    사용자가 원하는 카드 수령 방법을 추출하세요.
    
    선택지:
    - "영업점 방문": 직접 방문 수령
    - "택배 배송": 택배로 배송
    
    사용자 발화: "{user_input}"
    
    수령 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "직접 받으러 갈게요"
      output: "영업점 방문"
    - input: "택배로 보내주세요"
      output: "택배 배송"
    - input: "집으로 배송해주세요"
      output: "택배 배송"

cc_delivery_address:
  prompt: |
    사용자가 제공한 배송 주소를 추출하세요.
    
    추출 규칙:
    - 도로명 주소 또는 지번 주소
    - 시/구/동 등이 포함된 주소
    - 상세주소 포함
    
    사용자 발화: "{user_input}"
    
    배송 주소 (전체 주소, 없으면 null):
  examples:
    - input: "서울시 강남구 테헤란로 123 A동 1004호"
      output: "서울시 강남구 테헤란로 123 A동 1004호"
    - input: "주소는 경기도 성남시 분당구 판교로 100번지입니다"
      output: "경기도 성남시 분당구 판교로 100번지"

# deposit_account_scenario.json에 맞춘 추가 필드들

customer_phone:
  prompt: |
    사용자의 발화에서 휴대폰 번호를 추출하세요.
    
    추출 규칙:
    - 010으로 시작하는 11자리 번호
    - 하이픈(-), 공백은 포함하여 형식 유지
    - 다양한 형식 모두 인식
    
    사용자 발화: "{user_input}"
    
    추출된 번호 (하이픈 포함, 없으면 null):
  examples:
    - input: "010-1234-5678입니다"
      output: "010-1234-5678"
    - input: "번호는 010 9876 5432예요"
      output: "010-9876-5432"
    - input: "01011112222"
      output: "010-1111-2222"

use_internet_banking:
  prompt: |
    사용자가 인터넷뱅킹 가입 의사를 표현했는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 가입할게요, 사용할게요, 필요해요
    - 부정: 아니요, 안 할게요, 필요없어요, 나중에
    
    사용자 발화: "{user_input}"
    
    가입 의사 (true/false/null):
  examples:
    - input: "인터넷뱅킹 가입하겠습니다"
      output: true
    - input: "인터넷뱅킹은 필요없어요"
      output: false
    - input: "네, 할게요"
      output: true

security_medium:
  prompt: |
    사용자가 선택한 보안매체를 추출하세요.
    
    선택지:
    - "보안카드": 실물 카드
    - "신한 OTP": 신한은행 OTP
    - "타행 OTP": 다른 은행 OTP
    
    사용자 발화: "{user_input}"
    
    보안매체 (위 선택지 중 하나 또는 null):
  examples:
    - input: "보안카드로 할게요"
      output: "보안카드"
    - input: "신한 OTP 주세요"
      output: "신한 OTP"
    - input: "다른 은행 OTP 쓸게요"
      output: "타행 OTP"

other_otp_manufacturer:
  prompt: |
    타행 OTP의 제조사를 추출하세요.
    
    주요 제조사:
    - 농협, 국민, 우리, 하나, 기업, SC 등
    
    사용자 발화: "{user_input}"
    
    제조사명 (없으면 null):
  examples:
    - input: "농협에서 받은 OTP입니다"
      output: "농협"
    - input: "국민은행 OTP예요"
      output: "국민은행"

other_otp_serial:
  prompt: |
    타행 OTP의 일련번호를 추출하세요.
    
    추출 규칙:
    - 숫자와 영문자 조합
    - 6-10자리 정도
    
    사용자 발화: "{user_input}"
    
    일련번호 (없으면 null):
  examples:
    - input: "일련번호는 ABC123456입니다"
      output: "ABC123456"
    - input: "OTP 번호가 1234567890이에요"
      output: "1234567890"

transfer_limit_per_time:
  prompt: |
    사용자가 원하는 1회 이체한도를 추출하세요.
    
    추출 규칙:
    - 숫자만 추출 (단위: 만원)
    - 최대 5000만원
    
    사용자 발화: "{user_input}"
    
    한도 금액 (숫자만, 없으면 null):
  examples:
    - input: "1회 500만원으로 해주세요"
      output: 500
    - input: "한 번에 천만원까지"
      output: 1000
    - input: "회당 3천만원"
      output: 3000

transfer_limit_per_day:
  prompt: |
    사용자가 원하는 1일 이체한도를 추출하세요.
    
    추출 규칙:
    - 숫자만 추출 (단위: 만원)
    - 최대 1억원(10000만원)
    
    사용자 발화: "{user_input}"
    
    한도 금액 (숫자만, 없으면 null):
  examples:
    - input: "하루 5천만원 한도로"
      output: 5000
    - input: "1일 1억원"
      output: 10000
    - input: "일일 3천만원으로 해주세요"
      output: 3000

alert:
  prompt: |
    사용자가 선택한 알림 서비스를 추출하세요.
    
    선택지:
    - "문자": SMS 알림
    - "카카오톡": 카카오톡 알림
    - "모두": 문자와 카카오톡 모두
    - "안함": 알림 없음
    
    사용자 발화: "{user_input}"
    
    알림 방식 (위 선택지 중 하나 또는 null):
  examples:
    - input: "문자로 알려주세요"
      output: "문자"
    - input: "카톡으로 받을게요"
      output: "카카오톡"
    - input: "둘 다 받을게요"
      output: "모두"

additional_withdrawal_account:
  prompt: |
    사용자가 추가 출금계좌 등록을 원하는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 등록할게요, 추가할게요
    - 부정: 아니요, 안 할게요, 필요없어요
    
    사용자 발화: "{user_input}"
    
    등록 의사 (true/false/null):
  examples:
    - input: "추가 출금계좌 등록하겠습니다"
      output: true
    - input: "필요없어요"
      output: false

use_check_card:
  prompt: |
    사용자가 체크카드 발급을 원하는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 발급받을게요, 만들어주세요
    - 부정: 아니요, 안 할게요, 필요없어요
    
    사용자 발화: "{user_input}"
    
    발급 의사 (true/false/null):
  examples:
    - input: "체크카드도 만들어주세요"
      output: true
    - input: "체크카드는 안 할게요"
      output: false

card_receive_method:
  prompt: |
    사용자가 선택한 카드 수령 방법을 추출하세요.
    
    선택지:
    - "영업점": 영업점 방문 수령
    - "배송": 택배 배송
    
    사용자 발화: "{user_input}"
    
    수령 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "직접 받으러 갈게요"
      output: "영업점"
    - input: "택배로 보내주세요"
      output: "배송"

card_delivery_location:
  prompt: |
    사용자가 제공한 카드 배송 주소를 추출하세요.
    
    추출 규칙:
    - 전체 주소 추출
    - 도로명 또는 지번 주소
    
    사용자 발화: "{user_input}"
    
    배송 주소 (없으면 null):
  examples:
    - input: "서울시 강남구 테헤란로 123"
      output: "서울시 강남구 테헤란로 123"

card_type:
  prompt: |
    사용자가 선택한 체크카드 종류를 추출하세요.
    
    선택지:
    - "일반 체크": 일반 체크카드
    - "신한플레이": 신한플레이 체크카드
    - "마이신한포인트": 포인트 적립 체크카드
    
    사용자 발화: "{user_input}"
    
    카드 종류 (위 선택지 중 하나 또는 null):
  examples:
    - input: "일반 체크카드로 주세요"
      output: "일반 체크"
    - input: "신한플레이 카드로 할게요"
      output: "신한플레이"

postpaid_transport:
  prompt: |
    사용자가 후불교통 기능을 원하는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 신청할게요, 필요해요
    - 부정: 아니요, 안 할게요, 필요없어요
    
    사용자 발화: "{user_input}"
    
    신청 의사 (true/false/null):
  examples:
    - input: "후불교통 기능 넣어주세요"
      output: true
    - input: "후불교통은 필요없어요"
      output: false

payment_date:
  prompt: |
    사용자가 선택한 결제일을 추출하세요.
    
    추출 규칙:
    - 1일부터 28일 사이의 숫자
    - "일"이라는 단어와 함께 언급
    
    사용자 발화: "{user_input}"
    
    결제일 (숫자만, 없으면 null):
  examples:
    - input: "15일로 해주세요"
      output: 15
    - input: "결제일은 25일이요"
      output: 25
    - input: "매달 10일"
      output: 10

statement_method:
  prompt: |
    사용자가 선택한 이용명세서 수령 방법을 추출하세요.
    
    선택지:
    - "이메일": 이메일로 수령
    - "우편": 우편으로 수령
    - "안함": 수령 안함
    
    사용자 발화: "{user_input}"
    
    수령 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "이메일로 받을게요"
      output: "이메일"
    - input: "우편으로 보내주세요"
      output: "우편"
    - input: "명세서는 안 받을게요"
      output: "안함"

same_password_as_account:
  prompt: |
    사용자가 계좌 비밀번호와 동일하게 설정하기를 원하는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 같게 해주세요, 동일하게
    - 부정: 아니요, 다르게 할게요, 따로
    
    사용자 발화: "{user_input}"
    
    동일 설정 의사 (true/false/null):
  examples:
    - input: "계좌 비밀번호랑 같게 해주세요"
      output: true
    - input: "다른 비밀번호로 할게요"
      output: false

card_usage_alert:
  prompt: |
    사용자가 카드 사용 알림을 원하는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 알림 받을게요, 필요해요
    - 부정: 아니요, 안 받을게요, 필요없어요
    
    사용자 발화: "{user_input}"
    
    알림 신청 의사 (true/false/null):
  examples:
    - input: "카드 사용 알림 신청할게요"
      output: true
    - input: "알림은 필요없어요"
      output: false

# deposit_account_scenario_v3에 맞춘 추가 필드들

services_selected:
  prompt: |
    사용자가 선택한 서비스를 추출하세요.
    
    선택지:
    - "all": 모두 가입 (모바일 앱 + 체크카드)
    - "mobile_only": 모바일 앱만
    - "card_only": 체크카드만
    - "account_only": 입출금 계좌만
    
    판단 기준:
    - 모두/전부/다 → "all"
    - 모바일/앱 → "mobile_only"
    - 체크카드/카드 → "card_only"
    - 계좌만/입출금만 → "account_only"
    
    사용자 발화: "{user_input}"
    
    선택된 서비스 (위 선택지 중 하나 또는 null):
  examples:
    - input: "모두 가입할게요"
      output: "all"
    - input: "모바일 앱만 할게요"
      output: "mobile_only"
    - input: "체크카드만 발급해주세요"
      output: "card_only"
    - input: "입출금 계좌만 만들어주세요"
      output: "account_only"

personal_info_confirmed:
  prompt: |
    사용자가 개인정보 확인에 동의했는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 맞아요, 맞습니다, 확인했어요
    - 부정: 아니요, 틀려요, 수정할게요, 변경필요
    
    사용자 발화: "{user_input}"
    
    확인 여부 (true/false/null):
  examples:
    - input: "네, 맞습니다"
      output: true
    - input: "아니요, 수정이 필요해요"
      output: false

security_medium_selected:
  prompt: |
    사용자가 선택한 보안매체를 추출하세요.
    
    선택지:
    - "futuretech_19284019384": 미래테크 19284019384
    - "comas_rsa_12930295": 코마스(RSA) 12930295
    - "security_card": 보안카드
    - "shinhan_otp": 신한OTP
    
    판단 기준:
    - 미래테크 → "futuretech_19284019384"
    - 코마스/RSA → "comas_rsa_12930295"
    - 보안카드 → "security_card"
    - 신한OTP/OTP → "shinhan_otp"
    
    사용자 발화: "{user_input}"
    
    선택된 보안매체 (위 선택지 중 하나 또는 null):
  examples:
    - input: "미래테크로 할게요"
      output: "futuretech_19284019384"
    - input: "코마스 RSA로 등록해주세요"
      output: "comas_rsa_12930295"
    - input: "보안카드 발급받을게요"
      output: "security_card"

important_transaction_alert:
  prompt: |
    사용자가 중요거래 알림을 신청하는지 판단하세요.
    
    판단 기준:
    - 긍정: 신청, 네, 할게요
    - 부정: 미신청, 아니요, 안할게요
    
    사용자 발화: "{user_input}"
    
    신청 여부 ("신청"/"미신청"/null):
  examples:
    - input: "중요거래 알림 신청할게요"
      output: "신청"
    - input: "필요없어요"
      output: "미신청"

withdrawal_alert:
  prompt: |
    사용자가 출금 알림을 신청하는지 판단하세요.
    
    판단 기준:
    - 긍정: 신청, 네, 할게요
    - 부정: 미신청, 아니요, 안할게요
    
    사용자 발화: "{user_input}"
    
    신청 여부 ("신청"/"미신청"/null):
  examples:
    - input: "출금 알림도 신청해주세요"
      output: "신청"
    - input: "출금 알림은 안할게요"
      output: "미신청"

overseas_ip_restriction:
  prompt: |
    사용자가 해외 IP 이체 제한을 신청하는지 판단하세요.
    
    판단 기준:
    - 긍정: 신청, 네, 할게요
    - 부정: 미신청, 아니요, 안할게요
    
    사용자 발화: "{user_input}"
    
    신청 여부 ("신청"/"미신청"/null):
  examples:
    - input: "해외 IP 제한도 걸어주세요"
      output: "신청"
    - input: "해외 IP 제한은 필요없어요"
      output: "미신청"

card_selection:
  prompt: |
    사용자가 선택한 체크카드를 추출하세요.
    
    선택지:
    - "sline_transit": S-Line 체크카드 (후불교통)
    - "sline_regular": S-Line 체크카드 (일반)
    - "deepdream_transit": 신한 Deep Dream 체크카드 (후불교통)
    - "deepdream_regular": 신한 Deep Dream 체크카드 (일반)
    - "heyyoung_regular": 신한카드 Hey Young 체크카드 (일반)
    
    판단 기준:
    - S-Line + 후불교통 → "sline_transit"
    - S-Line + 일반 → "sline_regular"
    - Deep Dream + 후불교통 → "deepdream_transit"
    - Deep Dream + 일반 → "deepdream_regular"
    - Hey Young → "heyyoung_regular"
    
    사용자 발화: "{user_input}"
    
    선택된 카드 (위 선택지 중 하나 또는 null):
  examples:
    - input: "S-Line 후불교통 카드로 할게요"
      output: "sline_transit"
    - input: "Deep Dream 일반 카드로 주세요"
      output: "deepdream_regular"

statement_delivery_method:
  prompt: |
    사용자가 선택한 명세서 수령 방법을 추출하세요.
    
    선택지:
    - "mobile": 휴대폰
    - "email": 이메일
    - "website": 홈페이지
    
    판단 기준:
    - 휴대폰/문자 → "mobile"
    - 이메일/메일 → "email"
    - 홈페이지/웹사이트 → "website"
    
    사용자 발화: "{user_input}"
    
    수령 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "휴대폰으로 받을게요"
      output: "mobile"
    - input: "이메일로 보내주세요"
      output: "email"
    - input: "홈페이지에서 볼게요"
      output: "website"

card_password_same_as_account:
  prompt: |
    사용자가 카드 비밀번호를 계좌 비밀번호와 동일하게 설정하려는지 판단하세요.
    
    판단 기준:
    - 긍정: 네, 같게, 동일하게
    - 부정: 아니요, 다르게, 따로
    
    사용자 발화: "{user_input}"
    
    동일 설정 여부 (true/false/null):
  examples:
    - input: "계좌 비밀번호랑 같게 해주세요"
      output: true
    - input: "다른 비밀번호로 설정할게요"
      output: false