# 엔티티별 개별 추출 프롬프트 정의

customer_name:
  prompt: |
    사용자의 발화에서 고객 이름을 추출하세요.
    
    추출 규칙:
    - 한글 이름만 추출 (2-4자)
    - "~입니다", "~이에요", "~예요" 등의 표현에서 추출
    - 성과 이름이 함께 있어야 함
    
    사용자 발화: "{user_input}"
    
    추출된 이름 (없으면 null):
  examples:
    - input: "저는 김철수입니다"
      output: "김철수"
    - input: "이름은 박영희예요"
      output: "박영희"
    - input: "최민수라고 합니다"
      output: "최민수"

phone_number:
  prompt: |
    사용자의 발화에서 휴대폰 번호를 추출하세요.
    
    추출 규칙:
    - 010으로 시작하는 11자리 번호
    - 하이픈(-), 공백은 제거
    - 다양한 형식 모두 인식
    
    사용자 발화: "{user_input}"
    
    추출된 번호 (하이픈 없이, 없으면 null):
  examples:
    - input: "010-1234-5678입니다"
      output: "01012345678"
    - input: "번호는 010 9876 5432예요"
      output: "01098765432"
    - input: "01011112222"
      output: "01011112222"

use_lifelong_account:
  prompt: |
    사용자가 평생계좌 서비스 사용 의사를 표현했는지 판단하세요.
    
    판단 기준:
    - 평생계좌, 평생계좌번호 언급 시 의사 확인
    - 긍정: 사용, 할게요, 네, 좋아요
    - 부정: 안 써요, 필요없어요, 아니요
    
    사용자 발화: "{user_input}"
    
    사용 의사 (true/false/null):
  examples:
    - input: "평생계좌 사용하겠습니다"
      output: true
    - input: "평생계좌는 필요없어요"
      output: false
    - input: "평생계좌도 만들어주세요"
      output: true

ib_service_type:
  prompt: |
    사용자가 원하는 인터넷뱅킹 서비스 유형을 추출하세요.
    
    선택지:
    - "조회만": 잔액조회, 거래내역 조회만 가능
    - "조회+이체": 조회와 이체 모두 가능
    
    사용자 발화: "{user_input}"
    
    서비스 유형 (위 선택지 중 하나 또는 null):
  examples:
    - input: "조회만 되면 돼요"
      output: "조회만"
    - input: "이체도 할 수 있게 해주세요"
      output: "조회+이체"
    - input: "둘 다 가능하게 해주세요"
      output: "조회+이체"

ib_daily_limit:
  prompt: |
    사용자가 원하는 일일 이체 한도를 추출하세요.
    
    추출 규칙:
    - 숫자만 추출 (단위: 만원)
    - "백만원" → 100, "천만원" → 1000
    - 기본값은 제시하지 않음
    
    사용자 발화: "{user_input}"
    
    한도 금액 (숫자만, 없으면 null):
  examples:
    - input: "100만원으로 해주세요"
      output: 100
    - input: "한도는 500만원이요"
      output: 500
    - input: "천만원 한도로 설정해주세요"
      output: 1000

ib_security_method:
  prompt: |
    사용자가 원하는 보안 인증 방법을 추출하세요.
    
    선택지:
    - "SMS 인증": 문자 인증
    - "앱 인증": 모바일 앱 인증
    - "보안카드": 실물 보안카드
    
    사용자 발화: "{user_input}"
    
    인증 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "문자로 인증할게요"
      output: "SMS 인증"
    - input: "앱으로 하겠습니다"
      output: "앱 인증"
    - input: "보안카드 쓸게요"
      output: "보안카드"

cc_type:
  prompt: |
    사용자가 원하는 체크카드 종류를 추출하세요.
    
    선택지:
    - "일반형": 기본 체크카드
    - "교통카드형": 교통카드 기능 포함
    - "포인트적립형": 포인트 적립 기능
    
    사용자 발화: "{user_input}"
    
    카드 종류 (위 선택지 중 하나 또는 null):
  examples:
    - input: "그냥 일반 카드로 주세요"
      output: "일반형"
    - input: "교통카드 되는 걸로요"
      output: "교통카드형"
    - input: "포인트 쌓이는 걸로 할게요"
      output: "포인트적립형"

cc_delivery_method:
  prompt: |
    사용자가 원하는 카드 수령 방법을 추출하세요.
    
    선택지:
    - "영업점 방문": 직접 방문 수령
    - "택배 배송": 택배로 배송
    
    사용자 발화: "{user_input}"
    
    수령 방법 (위 선택지 중 하나 또는 null):
  examples:
    - input: "직접 받으러 갈게요"
      output: "영업점 방문"
    - input: "택배로 보내주세요"
      output: "택배 배송"
    - input: "집으로 배송해주세요"
      output: "택배 배송"

cc_delivery_address:
  prompt: |
    사용자가 제공한 배송 주소를 추출하세요.
    
    추출 규칙:
    - 도로명 주소 또는 지번 주소
    - 시/구/동 등이 포함된 주소
    - 상세주소 포함
    
    사용자 발화: "{user_input}"
    
    배송 주소 (전체 주소, 없으면 null):
  examples:
    - input: "서울시 강남구 테헤란로 123 A동 1004호"
      output: "서울시 강남구 테헤란로 123 A동 1004호"
    - input: "주소는 경기도 성남시 분당구 판교로 100번지입니다"
      output: "경기도 성남시 분당구 판교로 100번지"