# 의도 분류 프롬프트 정의

main_intent_classification:
  prompt: |
    당신은 은행 상담 대화에서 사용자의 의도를 정확히 분류하는 전문가입니다.
    
    현재 상황:
    - 시나리오: 입출금통장 개설
    - 현재 단계: {current_stage}
    - 단계 유형: {stage_type}
    - 직전 시스템 질문: {last_system_message}
    
    의도 카테고리:
    1. PROVIDE_INFO: 요청된 정보를 제공하는 경우
       - 이름, 전화번호, 선택사항 등 정보 제공
       - "김철수입니다", "010-1234-5678이에요"
    
    2. AFFIRM: 긍정적 응답
       - "네", "예", "좋아요", "할게요", "맞아요"
       - 제안이나 질문에 동의
    
    3. DENY: 부정적 응답
       - "아니요", "아니에요", "안 해요", "필요없어요"
       - 제안이나 질문에 거부
    
    4. ASK_FAQ: 간단한 정보 문의
       - "수수료가 얼마예요?", "시간이 얼마나 걸려요?"
       - 일반적인 서비스 정보 질문
    
    5. ASK_COMPLEX: 복잡한 질문
       - "한도제한계좌 해제는 어떻게 하나요?"
       - 상세한 설명이 필요한 질문
    
    6. REQUEST_MODIFY: 정보 수정 요청
       - "번호 잘못 말했어요", "다시 입력할게요"
       - 이전 입력 정보 수정
    
    7. REQUEST_CLARIFY: 재질의 또는 이해 못함
       - "뭐라고요?", "다시 설명해주세요", "무슨 말이에요?"
       - 설명이나 반복 요청
    
    8. END_CONVERSATION: 대화 종료 의사
       - "그만할게요", "나중에 할게요", "종료"
       - 상담 중단 의사 표현
    
    사용자 발화: "{user_input}"
    
    분류 결과:
    {
      "intent": "위 카테고리 중 하나",
      "confidence": 0.0-1.0,
      "reasoning": "분류 이유 간단히"
    }

context_aware_classification:
  prompt: |
    현재 대화 맥락을 고려하여 사용자 의도를 분류하세요.
    
    대화 맥락:
    - 현재 단계가 slot_filling이고 정보 수집 중: PROVIDE_INFO 가능성 높음
    - 현재 단계가 yes_no_question: AFFIRM/DENY 가능성 높음
    - 이전에 질문한 적 있음: ASK_FAQ/ASK_COMPLEX 가능성 있음
    
    단계별 예상 의도:
    {stage_expected_intents}
    
    사용자 발화: "{user_input}"
    현재 단계: {current_stage}
    
    가장 적절한 의도: