# 시나리오 유도 응답 템플릿
# 사용자가 시나리오에서 벗어난 질문을 했을 때 친절하게 답변하고 다시 시나리오로 유도하는 응답들

select_services:
  questions:
    한도계좌:
      keywords: ["한도계좌", "한도 계좌", "한도가 뭐", "한도계좌가 뭔가요"]
      response: "한도계좌는 정부에서 지원하는 특별한 계좌로, 일반 계좌보다 높은 금리와 세금 혜택을 받을 수 있어요. 1인당 최대 3개까지 가입 가능하고, 예금자보호 한도를 초과해도 원금과 이자를 보호받을 수 있습니다. 지금 한도계좌로 만드시면 모바일 앱과 체크카드도 함께 이용하실 수 있는데, 어떻게 하시겠어요?"
    
    인터넷뱅킹:
      keywords: ["인터넷뱅킹", "온라인뱅킹", "모바일뱅킹", "앱", "어플"]
      response: "인터넷뱅킹은 PC나 스마트폰으로 언제 어디서나 계좌 조회와 이체를 할 수 있는 서비스예요. 365일 24시간 이용 가능하고, 창구보다 수수료도 저렴합니다. 모바일 앱과 함께 신청하시면 더욱 편리하게 이용하실 수 있어요. 인터넷뱅킹도 함께 신청해드릴까요?"
    
    체크카드:
      keywords: ["체크카드", "체크 카드", "직불카드", "카드"]
      response: "체크카드는 계좌 잔액 범위 내에서 사용할 수 있는 카드로, 신용카드와 달리 연회비가 없고 과소비 걱정이 없어요. 교통카드 기능도 추가할 수 있어서 대중교통 이용도 편리합니다. 계좌 개설과 함께 체크카드도 만들어드릴까요?"
    
    비용:
      keywords: ["수수료", "비용", "돈", "얼마", "공짜", "무료"]
      response: "계좌 개설은 무료이고, 인터넷뱅킹도 가입비가 없어요. 체크카드도 연회비가 없습니다. 다만 타행 이체나 ATM 이용 시 소정의 수수료가 발생할 수 있는데, 한도계좌는 이런 수수료도 많이 면제됩니다. 지금 모든 서비스를 함께 신청하시겠어요?"

limit_account_guide:
  questions:
    한도:
      keywords: ["한도", "얼마까지", "최대", "제한"]
      response: "한도계좌는 1인당 최대 3개까지 가입 가능하고, 계좌당 예치 한도는 5천만원입니다. 3개 계좌를 합쳐서 최대 1억 5천만원까지 예치할 수 있어요. 예금자보호 한도인 5천만원을 초과해도 전액 보호받을 수 있다는 장점이 있습니다. 한도계좌로 진행하시겠어요?"
    
    금리:
      keywords: ["금리", "이자", "이율", "수익률"]
      response: "한도계좌는 일반 입출금 계좌보다 훨씬 높은 우대 금리를 제공합니다. 현재 기준금리에 추가 우대금리가 더해져서 시중 금리보다 높은 이자를 받으실 수 있어요. 정확한 금리는 가입 시점에 안내드리겠습니다. 한도계좌 개설에 동의하시겠어요?"
    
    자격:
      keywords: ["자격", "조건", "누가", "가능", "안되"]
      response: "한도계좌는 만 19세 이상 대한민국 국민이면 누구나 가입 가능해요. 다만 1인당 3개까지만 가입할 수 있고, 이미 3개를 보유하고 계시면 추가 가입이 안 됩니다. 고객님은 가입 가능하신 것으로 확인되는데, 한도계좌로 진행하시겠어요?"

security_medium_registration:
  questions:
    보안매체:
      keywords: ["보안매체", "OTP", "보안카드", "뭐가 좋", "차이"]
      response: "보안매체는 온라인 거래 시 본인 확인을 위한 도구입니다. OTP는 매번 새로운 일회용 비밀번호를 생성해서 가장 안전하고, 보안카드는 카드에 적힌 번호를 입력하는 방식이에요. 신한 OTP가 편리하고 안전해서 많이 사용하시는데, 신한 OTP로 등록해드릴까요?"
    
    이체한도:
      keywords: ["이체한도", "한도", "얼마까지", "송금", "이체"]
      response: "이체한도는 고객님의 자산을 보호하기 위해 설정하는 안전장치입니다. 1회 이체한도는 한 번에 보낼 수 있는 최대 금액이고, 1일 이체한도는 하루 동안 보낼 수 있는 총액이에요. 나중에 필요하시면 언제든 변경 가능합니다. 1회와 1일 이체한도를 각각 얼마로 설정하시겠어요?"
    
    변경:
      keywords: ["변경", "바꾸", "수정", "나중에"]
      response: "네, 보안매체나 이체한도는 나중에 언제든지 변경하실 수 있어요. 영업점 방문이나 인터넷뱅킹, 모바일앱에서 간단히 변경 가능합니다. 지금은 기본 설정으로 진행하고, 필요하시면 나중에 변경하시면 됩니다. 먼저 보안매체를 선택해주시겠어요?"

additional_services:
  questions:
    알림서비스:
      keywords: ["알림", "문자", "SMS", "알려", "통보"]
      response: "알림 서비스는 계좌의 안전을 위한 필수 서비스예요. 중요거래 알림은 10만원 이상 거래 시, 출금 알림은 모든 출금 내역을 실시간으로 알려드립니다. 해외IP 제한은 해외에서의 불법 접속을 차단해요. 모두 무료 서비스이니 전부 신청하시는 것을 추천드립니다. 어떻게 하시겠어요?"
    
    해외IP:
      keywords: ["해외IP", "해외", "외국", "여행", "출장"]
      response: "해외IP 제한은 해외에서 인터넷뱅킹 접속을 차단하는 보안 서비스입니다. 국내에서만 사용하신다면 꼭 신청하시는 게 좋고, 해외 출장이나 여행 시에는 잠시 해제할 수 있어요. 보안을 위해 신청하시는 것을 권해드립니다. 중요거래 알림, 출금 알림과 함께 모두 신청하시겠어요?"
    
    필요없어:
      keywords: ["필요없", "안해", "괜찮", "패스", "다음"]
      response: "알림 서비스는 무료이고 계좌 보안에 정말 중요해요. 특히 요즘 보이스피싱이나 해킹 시도가 많아서 꼭 필요한 서비스입니다. 나중에 해제도 가능하니 일단 신청해두시는 게 어떨까요? 안전한 금융거래를 위해 모두 신청해드릴게요. 괜찮으시죠?"

card_selection:
  questions:
    카드종류:
      keywords: ["어떤", "종류", "차이", "뭐가 좋", "추천"]
      response: "S-line은 깔끔한 디자인의 기본 카드이고, Deep Dream은 프리미엄 디자인 카드예요. Hey Young은 청년층을 위한 특별 디자인입니다. 교통카드 기능을 원하시면 '교통' 표시가 있는 카드를 선택하시면 됩니다. 가장 인기 있는 S-line 교통카드는 어떠신가요?"
    
    교통카드:
      keywords: ["교통카드", "버스", "지하철", "후불교통"]
      response: "후불교통 기능이 있는 카드를 선택하시면 버스나 지하철 탈 때 잔액 걱정 없이 사용하실 수 있어요. 사용한 교통비는 다음날 계좌에서 자동으로 출금됩니다. S-line 교통카드나 Deep Dream 교통카드를 추천드리는데, 어떤 디자인이 마음에 드시나요?"
    
    배송:
      keywords: ["배송", "받는", "수령", "언제", "며칠"]
      response: "체크카드는 영업점에서 즉시 수령하시거나 등록된 주소로 배송받으실 수 있어요. 즉시 수령은 당일 사용 가능하고, 배송은 3-5일 정도 걸립니다. 먼저 어떤 카드를 선택하실지 정하신 후에 수령 방법을 선택해주시면 됩니다. 어떤 카드를 선택하시겠어요?"

# 공통 질문들 (모든 단계에서 사용 가능)
common_questions:
  취소:
    keywords: ["취소", "그만", "안할래", "다음에", "나가"]
    response: "지금 중단하시면 처음부터 다시 진행하셔야 해요. 조금만 더 진행하시면 계좌 개설이 완료됩니다. 계속 진행하시는 게 어떨까요? 궁금하신 점이 있으시면 말씀해주세요."
  
  시간:
    keywords: ["얼마나", "시간", "오래", "빨리", "금방"]
    response: "계좌 개설은 약 10-15분 정도면 완료됩니다. 지금 절반 정도 진행하셨어요. 조금만 더 하시면 끝나니까 계속 진행하시죠. 현재 단계를 마저 진행해주시겠어요?"
  
  왜:
    keywords: ["왜", "이유", "필요한가", "꼭 해야"]
    response: "금융 거래의 안전과 법적 요구사항을 충족하기 위해 필요한 절차입니다. 고객님의 소중한 자산을 보호하기 위한 과정이니 양해 부탁드려요. 잠시만 시간을 내주시면 안전하게 계좌를 개설해드리겠습니다."