analyze_additional_services_choice: |
  당신은 은행 고객의 부가서비스 선택 의도를 정확히 분석하는 전문가입니다.
  
  **상황:** 
  고객이 입출금통장 개설 시 체크카드와 인터넷뱅킹 서비스 신청 여부를 묻는 질문에 답변했습니다.
  
  **원래 질문:**
  "혹시 체크카드나 인터넷뱅킹도 함께 신청하시겠어요? (예: 둘 다 신청, 체크카드만, 인터넷뱅킹만, 아니요)"
  
  **고객 답변:**
  "{user_input}"
  
  **분석 과제:**
  고객의 답변을 분석하여 다음 중 정확히 어느 의도에 해당하는지 판단하세요:
  
  1. **BOTH** - 체크카드와 인터넷뱅킹을 모두 신청하고 싶음
     - 예시: "둘다", "둘 다요", "모두 신청해주세요", "체크카드랑 인터넷뱅킹 다 해주세요", "네, 둘 다 필요해요"
  
  2. **CARD_ONLY** - 체크카드만 신청하고 싶음
     - 예시: "체크카드만", "카드만 있으면 돼요", "체크카드는 필요해요", "카드 하나만"
  
  3. **BANKING_ONLY** - 인터넷뱅킹만 신청하고 싶음
     - 예시: "인터넷뱅킹만", "온라인 뱅킹만", "인뱅만", "모바일뱅킹만 해주세요"
  
  4. **NONE** - 부가서비스를 신청하지 않음
     - 예시: "아니요", "필요없어요", "괜찮아요", "나중에 할게요", "기본 통장만"
  
  5. **UNCLEAR** - 의도가 불분명하거나 다른 질문을 하는 경우
     - 예시: "뭐가 좋을까요?", "차이점이 뭔가요?", "수수료는 얼마인가요?"
  
  **중요 지침:**
  - 고객의 **진짜 의도**를 파악하세요. 단순 키워드 매칭이 아닌 문맥상 의미를 이해하세요.
  - 애매한 표현("네", "좋아요")의 경우 UNCLEAR로 분류하세요.
  - 질문이나 추가 정보 요청은 UNCLEAR로 분류하세요.
  - 확실하지 않으면 UNCLEAR를 선택하세요.
  
  **출력 형식:**
  반드시 다음 JSON 형식으로만 응답하세요:
  
  {{
    "choice": "BOTH|CARD_ONLY|BANKING_ONLY|NONE|UNCLEAR",
    "confidence": 0.0-1.0,
    "reasoning": "판단 근거를 한 문장으로 설명"
  }}

normalize_additional_services_value: |
  사용자의 부가서비스 선택을 표준화된 값으로 변환하세요.
  
  **입력:**
  - 분석 결과: {analysis_result}
  - 원본 사용자 입력: "{user_input}"
  
  **변환 규칙:**
  - BOTH → "둘 다 신청"
  - CARD_ONLY → "체크카드만"  
  - BANKING_ONLY → "인터넷뱅킹만"
  - NONE → "아니요"
  - UNCLEAR → null (값을 설정하지 않음)
  
  **출력 형식:**
  {{
    "normalized_value": "표준화된 값 또는 null",
    "should_clarify": true/false,
    "clarification_needed": "명확화가 필요한 경우 이유"
  }}

determine_next_stage_smart: |
  입출금통장 상담에서 부가서비스 선택에 따른 다음 단계를 지능적으로 결정하세요.
  
  **현재 상황:**
  - 고객이 부가서비스 선택을 완료했습니다.
  - 수집된 정보: {collected_info}
  - 부가서비스 선택: "{additional_services_choice}"
  
  **가능한 다음 단계:**
  1. **ask_cc_issuance_method** - 체크카드 관련 설정 질문
     - 조건: 체크카드 신청이 포함된 경우
     
  2. **ask_ib_notification** - 인터넷뱅킹 관련 설정 질문
     - 조건: 인터넷뱅킹만 신청한 경우
     
  3. **final_summary_deposit** - 최종 요약 및 확인
     - 조건: 부가서비스를 신청하지 않은 경우
     
  4. **clarify_services** - 서비스 선택 재확인
     - 조건: 선택이 불분명한 경우
  
  **결정 로직:**
  - "둘 다 신청" 또는 "체크카드만" → ask_cc_issuance_method (체크카드부터 설정)
  - "인터넷뱅킹만" → ask_ib_notification
  - "아니요" → final_summary_deposit
  - null 또는 불분명 → clarify_services
  
  **출력 형식:**
  {{
    "next_stage_id": "선택된 다음 단계 ID",
    "reasoning": "선택 근거"
  }}