# 신한은행 주요 서비스 설명
# 이 파일은 main_agent의 business_guidance_prompt에서 사용됩니다

didimdol:
  name: "디딤돌 대출"
  target: "무주택 서민 (연소득 6-7천만원 이하)"
  summary: |
    정부 지원 주택구입자금 대출로, 생애최초 구입자는 최대 3억원, 신혼부부와 2자녀 이상 가구는 최대 4억원까지 
    연 2.15~2.75%의 저금리로 지원합니다. 우대조건 충족 시 추가 금리 인하 혜택을 받을 수 있습니다.
  benefits:
    - "저금리: 연 2.15~2.75% (시중 대출 대비 2~3% 낮음)"
    - "고액 한도: 최대 4억원 (신혼부부/2자녀 이상)"
    - "장기 상환: 10년, 15년, 20년, 30년 선택 가능"
    - "중도상환수수료 면제"

jeonse:
  name: "전세 대출"
  target: "무주택 세대주 (전세계약 체결자)"
  summary: |
    전세 보증금 마련을 위한 대출로, 임차보증금의 최대 80-90% 범위 내에서 지원합니다. 
    일반 전세대출은 최대 5억원, 청년 전세대출은 최대 2억원까지 가능하며, 만기일시상환 방식으로 운영됩니다.
  benefits:
    - "높은 한도: 보증금의 최대 90%까지"
    - "편리한 상환: 이자만 납부, 만기 시 원금 상환"
    - "안정적 주거: 임대차 기간 동안 주거 안정성 확보"
    - "청년 우대: 만 34세 이하 청년 특별 금리"

deposit_account:
  name: "입출금통장"
  target: "모든 고객"
  summary: |
    일상 금융거래를 위한 기본 계좌로, 신규 개설 시 금융사기 예방을 위해 한도제한계좌로 시작됩니다.
    평생계좌 서비스로 휴대폰 번호를 계좌번호로 사용할 수 있어 편리합니다.
  benefits:
    - "평생계좌: 휴대폰 번호로 간편 송금"
    - "부가서비스: 체크카드, 인터넷뱅킹 동시 신청"
    - "수수료 우대: 타행 이체 및 ATM 수수료 면제"
    - "모바일 완결: 비대면 계좌 개설 가능"

# 서비스 선택 안내 메시지
service_selection_guide: |
  고객님의 금융 니즈에 맞는 서비스를 추천해드립니다:
  • 내 집 마련이 목표이신가요? → 디딤돌 대출
  • 전세 자금이 필요하신가요? → 전세 대출  
  • 일상 금융거래 계좌가 필요하신가요? → 입출금통장